In [1]:
from eda_imports import *

import pysam

import kleat.misc.settings as S
import kleat.misc.utils as U

In [14]:
lele = pd.read_pickle('../benchmark_transcriptome/after-num-suffix-reads-fix-renamed-header/HBRC4.ml_ready.pkl')

In [16]:
lele.shape

(931053, 66)

In [15]:
lele.head(2)

,seqname,strand,clv,aclv,gene_name,gene_id,signed_dist_to_aclv,evidence_type,contig_ids_at_pos,any_contig_is_hardclipped,contig_max_len,contig_max_mapq,num_contigs_suffix,num_contigs_bridge,num_contigs_link,num_contigs_blank,num_total_contigs,num_reads_suffix,num_reads_bridge,num_reads_link,max_read_tail_len_suffix,max_read_tail_len_bridge,max_contig_tail_len_suffix,ctg_hex,ctg_hex_id,ctg_hex_pos,ctg_hex_dist,ref_hex,ref_hex_id,ref_hex_pos,ref_hex_dist,abs_dist_to_aclv,ctg_AAAAAG,ctg_AAAACA,ctg_AAGAAA,ctg_AATAAA,ctg_AATACA,ctg_AATAGA,ctg_AATATA,ctg_AATGAA,ctg_ACTAAA,ctg_AGTAAA,ctg_ATTAAA,ctg_CATAAA,ctg_GATAAA,ctg_GGGGCT,ctg_NA,ctg_TATAAA,ctg_TTTAAA,ref_AAAAAG,ref_AAAACA,ref_AAGAAA,ref_AATAAA,ref_AATACA,ref_AATAGA,ref_AATATA,ref_AATGAA,ref_ACTAAA,ref_AGTAAA,ref_ATTAAA,ref_CATAAA,ref_GATAAA,ref_GGGGCT,ref_NA,ref_TATAAA,ref_TTTAAA
0,chr1,+,12556,13671,DDX11L1,ENSG00000223972,-1115,blank,01.S.508265@110,True,3,0,0,0,0,1,1,0,0,0,0,0,0,AAGAAA,5,12543,13,AAGAAA,5,12543,13,1115,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,chr1,+,14602,14413,DDX11L1,ENSG00000223972,189,blank,E2.L.2150@240,True,3,0,0,0,0,1,1,0,0,0,0,0,0,NA,-1,-1,-1,NA,-1,-1,-1,189,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [3]:
dfs = []
for i in glob.glob('../max_recall.*'):
    dfs.append(pd.read_csv(i, sep='\t'))

In [6]:
ndf = pd.concat(dfs).sort_values('sample_id')

In [7]:
ndf

  sample_id  precision    recall        f1
0  HBRC4     0.026774   0.242732  0.048228
0  HBRC6     0.014323   0.359445  0.027547
0  UHRC1     0.025576   0.198304  0.045308
0  UHRC2     0.023578   0.222404  0.042635

In [8]:
df_kleat2 = pd.read_csv('/projects/btl/zxue/tasrkleat-TCGA-results/tasrkleat-TCGA-analysis-scripts/benchmark-kleat.bk/UHR/C1/tasrkleat-results/kleat/cba.KLEAT', sep='\t')
df_kleat2.head(2)

In [12]:
df_kleat2.sort_values('number_of_tail_reads', ascending=False).head(10)

,gene,transcript,transcript_strand,coding,contig,chromosome,cleavage_site,within_UTR,distance_from_annotated_site,ESTs,length_of_tail_in_contig,number_of_tail_reads,number_of_bridge_reads,max_bridge_read_tail_length,bridge_read_identities,tail+bridge_reads,number_of_link_pairs,max_link_pair_length,link_pair_identities,hexamer_loc+id,3UTR_start_end,flag
2058,GNAS,ENST00000371095,+,yes,"A0.R100623,A0.J100905",chr20,57486247,yes,0,0,16,20,0,0,-,20,0,0,-,-,-,1
499,FGFR3,ENST00000481110,+,yes,"A0.R100856,A0.J100703",chr4,1810594,yes,2,0,13,12,0,0,-,12,0,0,-,1810573:1,-,1
1817,SMARCA4,ENST00000450717,+,yes,"A0.R100671,A1.S26663,A0.J100737",chr19,11172953,yes,5,0,14,9,0,0,-,9,0,0,-,11172927:1,-,1
1284,AKT1,ENST00000407796,-,yes,"A1.R26107,A1.S26628,A0.R100669",chr14,105235686,yes,1,0,12,8,0,0,-,8,0,0,-,105235705:1,-,1
604,RHOBTB3,ENST00000379982,+,yes,A0.R100765,chr5,95130822,yes,1249,0,4,8,0,0,-,8,0,0,-,-,-,1
1040,HRAS,ENST00000451590,-,yes,"A1.R26175,A1.R26487,A1.S26555",chr11,532242,yes,0,0,11,7,0,0,-,7,0,0,-,532264:3,-,1
1880,CEBPA,ENST00000498907,-,yes,A0.S101662,chr19,33790840,yes,1,0,9,7,0,0,-,7,0,0,-,33790859:4,-,1
724,HNRNPA2B1,ENST00000356674,-,yes,A0.S32990,chr7,26232870,yes,1407,0,1,6,0,0,-,6,0,0,-,-,-,1
1396,BLOC1S6,ENST00000567523,+,yes,A0.R101303,chr15,45899979,yes,8,0,2,6,0,0,-,6,0,0,-,-,-,1
1547,CDH1,ENST00000261769,+,yes,A0.R100743,chr16,68869444,yes,7,0,8,6,0,0,-,6,0,0,-,-,-,1

In [2]:
sys.path.insert(0, '../../kleat/benchmark_scripts/')

In [3]:
# from train_arbor import cluster_clv, compare

In [13]:
from max_recall_analysis import cluster_clv_parallel, map_to_ref

# Compare current version and a previous ref-hex-dist version

In [5]:
cur_df = pd.read_pickle('./../../kleat/benchmark_transcriptome/current-buggy/UHRC1.pkl')

In [6]:
cur_df.shape

(869893, 30)

In [7]:
%time cur_df_clustered = cluster_clv_parallel(cur_df)

2018-07-17 14:29:05,229|INFO|grouping by ['seqname', 'strand']
100%|██████████| 50/50 [00:00<00:00, 139.83it/s]

clustering clvs in parallel) using 24 CPUs ...

2018-07-17 14:30:00,349|INFO|concatenating clustered sub dataframes ...
2018-07-17 14:30:01,181|INFO|dropping duplicates after clustering ...

CPU times: user 21.6 s, sys: 3.5 s, total: 25.1 s
Wall time: 57 s

In [8]:
%time ref_df = pd.read_pickle('./../../kleat/benchmark_transcriptome/after_chimeric-ref-hex/UHRC1.pkl')

CPU times: user 2.4 s, sys: 460 ms, total: 2.86 s
Wall time: 2.86 s

In [9]:
ref_df.shape

(869986, 30)

In [10]:
%time ref_df_clustered = cluster_clv_parallel(ref_df)

2018-07-17 14:30:38,580|INFO|grouping by ['seqname', 'strand']
100%|██████████| 50/50 [00:00<00:00, 163.00it/s]

clustering clvs in parallel) using 24 CPUs ...

2018-07-17 14:31:33,376|INFO|concatenating clustered sub dataframes ...
2018-07-17 14:31:34,184|INFO|dropping duplicates after clustering ...

CPU times: user 21.9 s, sys: 3.01 s, total: 24.9 s
Wall time: 56.9 s

In [11]:
ref_df_clustered.shape

(805439, 3)

In [14]:
print('mapping ...')
map_cutoff = 50
df_mapped = map_to_ref(cur_df_clustered, ref_df_clustered, map_cutoff)
df_mapped['is_tp'] = df_mapped.abs_dist < map_cutoff

2018-07-17 14:33:38,391|INFO|mapping predicted clv to ground truth ...

mapping ...

In [16]:
print('calculating metrics ...')
recall = df_mapped.query('is_tp').shape[0] / ref_df_clustered.shape[0]
precision = df_mapped.query('is_tp').shape[0] / df_mapped.shape[0]
f1 = (2 * recall * precision) / (recall + precision)

calculating metrics ...

In [20]:
print(f'{precision}\t{recall}\t{f1}')

0.9997479250381217	0.9995952517819475	0.9996715825808393

In [21]:
df_mapped.head(2)

  seqname strand    clv  mapped_ref_clv  dist  abs_dist  is_tp
0  chr1    +      12199  12199           0     0         True
1  chr1    +      14748  14748           0     0         True

In [4]:
cur_df['clv_m1'] = cur_df.clv - 1
cur_df['clv_p1'] = cur_df.clv + 1

In [5]:
cur_clvs_m1 = set([tuple(_) for _ in cur_df[['seqname', 'strand', 'clv_m1']].values])
cur_clvs    = set([tuple(_) for _ in cur_df[['seqname', 'strand', 'clv'   ]].values])
cur_clvs_p1 = set([tuple(_) for _ in cur_df[['seqname', 'strand', 'clv_p1']].values])

In [6]:
cur_clvs_set = cur_clvs_m1 | cur_clvs | cur_clvs_p1

In [7]:
len(cur_clvs_set)

2577194

In [8]:
len(cur_clvs_m1) + len(cur_clvs) + len(cur_clvs_p1)

2609679

In [15]:
%time ref_clvs = set([tuple(_) for _ in ref_df[['seqname', 'strand', 'clv']].values])

CPU times: user 1.35 s, sys: 32.9 ms, total: 1.38 s
Wall time: 1.38 s

In [16]:
len(ref_clvs - cur_clvs_set)

534

In [17]:
len(cur_clvs_set - ref_clvs)

1707742

In [18]:
missed = ref_clvs - cur_clvs_set

In [19]:
list(missed)[:5]

[('chr7', '+', 73660993),
 ('chr6', '+', 75950892),
 ('chr19', '+', 649680),
 ('chr16', '-', 78534894),
 ('chr13', '+', 40914558)]

In [20]:
missed_clvs = [_[2] for _ in missed]

In [35]:
missed_df = ref_df.query(f'clv in {missed_clvs}').copy()

In [36]:
missed_df.evidence_type.value_counts()

bridge    534
blank     10
Name: evidence_type, dtype: int64

In [37]:
missed_df['abs_dist_to_aclv'] = missed_df.signed_dist_to_aclv.abs()

In [41]:
missed_df.query('evidence_type == "bridge"')\
    .query('ref_hex == "AATAAA"').sort_values('abs_dist_to_aclv').head(10)

,seqname,strand,clv,aclv,gene_name,gene_id,signed_dist_to_aclv,evidence_type,contig_ids,max_contig_len,max_contig_mapq,any_contig_is_hardclipped,num_suffix_contigs,num_bridge_contigs,num_link_contigs,num_blank_contigs,num_total_contigs,num_suffix_reads,max_suffix_contig_tail_len,num_bridge_reads,max_bridge_read_tail_len,num_link_reads,ctg_hex,ctg_hex_id,ctg_hex_pos,ctg_hex_dist,ref_hex,ref_hex_id,ref_hex_pos,ref_hex_dist,abs_dist_to_aclv
657410,chr5,-,74017080,74017083,GFM2,ENSG00000164347,-3,bridge,E0.L.64191,963,40,False,0,1,0,0,1,0,0,2,5,0,AATAAA,16,74017103,23,AATAAA,16,74017105,25,3
798032,chr8,-,144668458,144668388,EEF1D,ENSG00000104529,70,bridge,E1.L.11467,1298,40,False,0,1,0,0,1,0,0,1,1,0,AATAAA,16,144668497,39,AATAAA,16,144668497,39,70
824660,chr9,-,99314154,99314082,CDC14B,ENSG00000081377,72,bridge,E1.L.4856,2381,40,False,0,1,0,0,1,0,0,2,2,0,AATAAA,16,99314188,34,AATAAA,16,99314188,34,72
245655,chr14,-,50050393,50050296,RPS29,ENSG00000213741,97,bridge,E1.L.7611,401,40,False,0,1,0,0,1,0,0,2,2,0,AATAAA,16,50050420,27,AATAAA,16,50050420,27,97
439840,chr2,+,170492976,170492752,PPIG,ENSG00000138398,224,bridge,E0.L.63481,374,0,True,0,1,0,0,1,0,0,2,1,0,NA,-1,-1,-1,AATAAA,16,170492937,39,224
443718,chr2,+,198367763,198368020,HSPE1,ENSG00000115541,-257,bridge,E3.L.197,616,40,False,0,1,0,0,1,0,0,4,2,0,AATAAA,16,198367738,25,AATAAA,16,198367738,25,257
477802,chr2,-,198360099,198359774,HSPD1,ENSG00000144381,325,bridge,E3.L.96,1923,40,False,0,1,0,0,1,0,0,6,2,0,AATAAA,16,198360134,35,AATAAA,16,198360134,35,325
833396,chrM,+,997,648,MT-TF,ENSG00000210049,349,bridge,E0.L.43441,274,0,True,0,1,0,0,1,0,0,1,2,0,NA,-1,-1,-1,AATAAA,16,967,30,349
550652,chr3,+,101284073,101284562,TRMT10C,ENSG00000174173,-489,bridge,E0.S.109816,106,40,True,0,1,0,0,1,0,0,6,5,0,NA,-1,-1,-1,AATAAA,16,101284065,8,489
712114,chr6,-,135307948,135308791,HBS1L,ENSG00000112339,-843,bridge,E2.L.2538,2699,40,False,0,1,0,0,1,0,0,2,2,0,AATAAA,16,135307968,20,AATAAA,16,135307968,20,843

In [44]:
cur_df[cur_df.contig_ids.str.contains('E1.L.11467')]

,seqname,strand,clv,aclv,gene_name,gene_id,signed_dist_to_aclv,evidence_type,contig_ids,max_contig_len,max_contig_mapq,any_contig_is_hardclipped,num_suffix_contigs,num_bridge_contigs,num_link_contigs,num_blank_contigs,num_total_contigs,num_suffix_reads,max_suffix_contig_tail_len,num_bridge_reads,max_bridge_read_tail_len,num_link_reads,ctg_hex,ctg_hex_id,ctg_hex_pos,ctg_hex_dist,ref_hex,ref_hex_id,ref_hex_pos,ref_hex_dist,clv_m1,clv_p1
781363,chr8,+,144677134,144682485,TIGD5,ENSG00000179886,-5351,blank,E1.L.11467,1298,40,False,0,0,0,1,1,0,0,0,0,0,NA,-1,-1,-1,NA,-1,-1,-1,144677133,144677135
797962,chr8,-,144663470,144663248,EEF1D,ENSG00000104529,222,blank,E0.S.110148|E1.L.11467,1298,40,False,0,0,0,2,2,0,0,0,0,0,NA,-1,-1,-1,NA,-1,-1,-1,144663469,144663471
797971,chr8,-,144668898,144668898,EEF1D,ENSG00000104529,0,blank|bridge,E0.U.122352|E1.L.11467,1298,40,False,0,1,0,1,2,0,0,1,1,0,NA,-1,-1,-1,NA,-1,-1,-1,144668897,144668899

In [26]:
cur_df.query('clv == 74017082')

,seqname,strand,clv,aclv,gene_name,gene_id,signed_dist_to_aclv,evidence_type,contig_ids,max_contig_len,max_contig_mapq,any_contig_is_hardclipped,num_suffix_contigs,num_bridge_contigs,num_link_contigs,num_blank_contigs,num_total_contigs,num_suffix_reads,max_suffix_contig_tail_len,num_bridge_reads,max_bridge_read_tail_len,num_link_reads,ctg_hex,ctg_hex_id,ctg_hex_pos,ctg_hex_dist,ref_hex,ref_hex_id,ref_hex_pos,ref_hex_dist,clv_m1,clv_p1
657356,chr5,-,74017082,74017083,GFM2,ENSG00000164347,-1,bridge,E0.L.64191|E0.U.323536,963,40,False,0,2,0,0,2,0,0,4,5,0,AATAAA,16,74017105,23,AATAAA,16,74017105,23,74017081,74017083

In [42]:
# missed_df.query('evidence_type == "bridge"').query('signed_dist_to_aclv <= 0').sort_values('signed_dist_to_aclv', ascending=False)\
#     .head(10).reset_index(drop=True).iloc[5:]

In [24]:
cur_df.query('contig_ids == "01.U.576215"')

,seqname,strand,clv,aclv,gene_name,gene_id,signed_dist_to_aclv,evidence_type,contig_ids,max_contig_len,max_contig_mapq,any_contig_is_hardclipped,num_suffix_contigs,num_bridge_contigs,num_link_contigs,num_blank_contigs,num_total_contigs,num_suffix_reads,max_suffix_contig_tail_len,num_bridge_reads,max_bridge_read_tail_len,num_link_reads,ctg_hex,ctg_hex_id,ctg_hex_pos,ctg_hex_dist,ref_hex,ref_hex_id,ref_hex_pos,ref_hex_dist,clv_m1,clv_p1
812011,chr9,+,129638500,129648154,ZBTB34,ENSG00000177125,-9654,blank,01.U.576215,42,0,True,0,0,0,1,1,0,0,0,0,0,NA,-1,-1,-1,NA,-1,-1,-1,129638499,129638501

In [27]:
missed_df.query('evidence_type == "bridge"').sort_values('num_bridge_reads', ascending=False).head()

,seqname,strand,clv,aclv,gene_name,gene_id,signed_dist_to_aclv,evidence_type,contig_ids,max_contig_len,max_contig_mapq,any_contig_is_hardclipped,num_suffix_contigs,num_bridge_contigs,num_link_contigs,num_blank_contigs,num_total_contigs,num_suffix_reads,max_suffix_contig_tail_len,num_bridge_reads,max_bridge_read_tail_len,num_link_reads,ctg_hex,ctg_hex_id,ctg_hex_pos,ctg_hex_dist,ref_hex,ref_hex_id,ref_hex_pos,ref_hex_dist
288391,chr16,+,16388114,16388135,NOMO3,ENSG00000103226,-21,bridge,01.L.377168,184,0,True,0,1,0,0,1,0,0,67,2,0,NA,-1,-1,-1,NA,-1,-1,-1
718349,chr7,+,5566820,5596877,CTB-161C1.1,ENSG00000272719,-30057,bridge,E0.L.69552,267,40,True,0,1,0,0,1,0,0,26,7,0,NA,-1,-1,-1,NA,-1,-1,-1
639318,chr5,+,117081763,116881994,LINC00992,ENSG00000248663,199769,bridge,01.U.677024,75,4,False,0,1,0,0,1,0,0,15,24,0,NA,-1,-1,-1,NA,-1,-1,-1
706718,chr6,-,79918293,79910962,HMGN3,ENSG00000118418,7331,bridge,E2.L.1715,856,40,False,0,1,0,0,1,0,0,13,2,0,NA,-1,-1,-1,NA,-1,-1,-1
629627,chr5,+,33631226,33503241,CTD-2233C11.3,ENSG00000249360,127985,bridge,01.U.1059438,75,40,False,0,1,0,0,1,0,0,12,10,0,NA,-1,-1,-1,NA,-1,-1,-1